[package]
name = "sbbarch_mastodon"
version = "0.1.0"
edition = "2021"

[dependencies]
enumscribe = { version = "0.4.0", default-features = false, features = ["std", "derive"] }
html5ever = "0.26.0"
libshire = { git = "https://github.com/pantonshire/libshire" }
markup5ever_rcdom = "0.2.0"
